
FROM mcr.microsoft.com/powershell:lts-nanoserver-1809

# old cross platform SMALL image that is unmaintained
# FROM mcr.microsoft.com/powershell

COPY webserver.ps1 /

ENTRYPOINT [ "pwsh", "/webserver.ps1" ]

USER ContainerAdministrator